#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-bionic AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["InternalSurvey.Api/InternalSurvey.Api.csproj", "InternalSurvey.Api/"]
RUN dotnet restore "InternalSurvey.Api/InternalSurvey.Api.csproj"
COPY . .
WORKDIR "/src/InternalSurvey.Api"
RUN dotnet build "InternalSurvey.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "InternalSurvey.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app

COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "InternalSurvey.Api.dll"]